server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
    
#Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka